### ISSUE TITLE
rgi heatmap issue

### ISSUE THREAD

**Issue by justabit96** [arpcard/rgi#141]
Hello everyone. I got a problem when I run rgi heatmap. I tried to update pandas but the problem remains. Could you help me? Thanks a lot! 
I put in the result_heatmap folder all the .json files that have been produced after running rgi bwt with FASTAQ files.

Maybe the problem is that the output file format is not fasta.json but .json. It could be?

rgi heatmap --input heatmap/ -o /home/STUDENTI/luca.rubinetti/result_heatmap -cat drug_class -clus samples

Traceback (most recent call last):
  File "/home/STUDENTI/luca.rubinetti/anaconda3/envs/rgi/bin/rgi", line 4, in <module>
    MainBase()
  File "/home/STUDENTI/luca.rubinetti/anaconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 82, in __init__
    getattr(self, args.command)()
  File "/home/STUDENTI/luca.rubinetti/anaconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 336, in heatmap
    self.heatmap_run(args)
  File "/home/STUDENTI/luca.rubinetti/anaconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 357, in heatmap_run
    obj.run()
  File "/home/STUDENTI/luca.rubinetti/anaconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 455, in run
    complete_class_df= complete_class_df.set_index(["resistance_mechanism", "gene_family"], append=True)["drug_class"].apply(pd.Series).stack()
  File "/home/STUDENTI/luca.rubinetti/anaconda3/envs/rgi/lib/python3.8/site-packages/pandas/core/generic.py", line 5462, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'stack'

**Comment by raphenya** [comment]
@justabit96 `rgi heatmap` only works with `jsons` from `rgi main` and not `rgi bwt`.

**Comment by neelam19051** [comment]
Hi, i have around 400 genome could you please tell me, how to make an effective RGI heatmap because when i am running rgi the output figure is not so clear. So basically all of the strain not clearly visible. Can you tell me how to change axis because i have seen it the genome are aligned in heatmap on x axis and i want to change it on y axis...

**Comment by raphenya** [comment]
@neelam19051 I will advise splitting your inputs if the labels are hard to see.
