### ISSUE TITLE
Incomplete database install in docker container 

### ISSUE THREAD

**Issue by tpillone** [arpcard/rgi#155]
Hi,

I'm trying to build a singularity container from the rgi docker image.
I'm facing problems due to the fact that the database install seems to be incomplete in the docker image. Indeed, when I run the singularity container, rgi tries to write a fasta file in the database folder (see error message below). 
Would it be possible to have a complete database install in the docker container that would not require to write additional files in the database folder when running rgi?

**# commands**
singularity build rgi_latest.simg docker://finlaymaguire/rgi:latest
singularity exec rgi_latest.simg /opt/conda/envs/rgi/bin/rgi main -t contig -i 1052_1458.fna -n 4 -o test

**# error message** 
Traceback (most recent call last):
  File "/opt/conda/envs/rgi/bin/rgi", line 4, in <module>
    MainBase()
  File "/opt/conda/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 82, in __init__
    getattr(self, args.command)()
  File "/opt/conda/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 87, in main
    self.main_run(args)
  File "/opt/conda/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 121, in main_run
    rgi_obj.run()
  File "/opt/conda/envs/rgi/lib/python3.8/site-packages/app/RGI.py", line 251, in run
    self.create_databases()
  File "/opt/conda/envs/rgi/lib/python3.8/site-packages/app/RGI.py", line 245, in create_databases
    db_obj.build_databases()
  File "/opt/conda/envs/rgi/lib/python3.8/site-packages/app/Database.py", line 22, in build_databases
    self.write_fasta_from_json()
  File "/opt/conda/envs/rgi/lib/python3.8/site-packages/app/Database.py", line 68, in write_fasta_from_json
    with open(os.path.join(self.db, "proteindb.fsa"), 'w') as fout:
OSError: [Errno 30] Read-only file system: '/opt/conda/envs/rgi/lib/python3.8/site-packages/app/_db/proteindb.fsa'

**Comment by innovate-invent** [comment]
I have also encountered this problem, the issue is that the paths are not configurable: https://github.com/arpcard/rgi/blob/e2cb7238181b65762d5963cd54c51c4cec8cb05c/app/settings.py#L31-L32

**Comment by innovate-invent** [comment]
There appears to be a workaround where you set the `--local` flag and it will use the current working directory.
