### ISSUE TITLE
Can't create conda environment and run rgi main

### ISSUE THREAD

**Issue by TommyH-Tran** [arpcard/rgi#166]
I am using WSL2 linux through Ubuntu 20.04 LTS. I am trying to run the rgi main command. However, I think I am missing some dependencies even though I have tried to install them. So I back tracked to the install dependencies step on the READ.Me file. I am using the developing version when using git clone. I am not sure the exact issue(s) Ihave at hand and the steps I need to take. 

This is what happened when I tried to create the conda environment

```
(base) tommy@DESKTOP-D59L9FO:/mnt/c/Users/12542/Downloads/rgi$ ls
CITATION.cff  LICENSE     app        card_database_v3.1.3.fasta  data  images   requirements.txt  rgi_autoload_2yzbz1q0  test.sh  wildcard_database_v3.0.9.fasta
Dockerfile    README.rst  card.json  conda_env.yml               docs  localDB  rgi               setup.py               tests
(base) tommy@DESKTOP-D59L9FO:/mnt/c/Users/12542/Downloads/rgi$ conda env create -f conda_env.yml
Traceback (most recent call last):
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/home/tommy/.local/lib/python3.8/site-packages/requests/__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tommy/miniconda3/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 13, in <module>
    import conda.exports  # noqa
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda/plan.py", line 25, in <module>
    from .core.index import LAST_CHANNEL_URLS, _supplement_index_with_prefix
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 13, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/home/tommy/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/__init__.py", line 39, in <module>
    from pip._vendor.requests import ConnectionError, HTTPError, Session
ModuleNotFoundError: No module named 'pip'
(base) tommy@DESKTOP-D59L9FO:/mnt/c/Users/12542/Downloads/rgi$
```

**Comment by raphenya** [comment]
@TommyH-Tran tested the following on macOS and Linux and it works fine: 
```
# install dependencies
git clone https://github.com/arpcard/rgi
conda env create -f conda_env.yml
conda activate rgi

# install rgi 
pip install git+https://github.com/arpcard/rgi.git
```
