### ISSUE TITLE
Error while running RGI for loose hit, without nudging

### ISSUE THREAD

**Issue by absartalat** [arpcard/rgi#171]
When I run RGI with the parameter LOOSE hit, I get an error. I have used both nucleotide fasta file as well as protein fasta file. Both give error.

**Input**
$ rgi main --input_sequence Sample_2.fasta   --output_file Sample_1rgi_loose --input_type contig --local   --include_loose --clean

**Error log**
Process Process-2:
Traceback (most recent call last):
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/site-packages/app/Filter.py", line 92, in prepare_output
    obj.combine_jsons()
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/site-packages/app/ConvertRGIJsonToTSV.py", line 39, in combine_jsons
    homolog = json.load(hf)
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/s2/anaconda3/envs/rgi/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**CARD Version**
card_database_v3.1.1

**RGI version**
5.2.0

**Expected behavior**
I expect it to give an output file of all the resistome having loose hits in eference to CARD

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
If applicable, include dependency versions such as Biopython version and Python version.

**Comment by raphenya** [comment]
@absartalat This looks like there was an issue with the JSON file as it was empty. It will help if you have a sample input file so we can try debugging. Please re-open the issue if you still need help on this. Cheers.
