### ISSUE TITLE
Bio.alphabet issue[BUG]

### ISSUE THREAD

**Issue by yasiromics** [arpcard/rgi#187]
Hi all!
I am trying to install RGI. After I download the CARD reference data and unpack the zipped file, I use this command
rgi load --card_json ./card.json --local
However, I am getting an error related to the Bio.alphabet. The error goes like this:

Traceback (most recent call last):
  File "/home/drasadukhan/miniconda3/envs/RGI/bin/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/home/drasadukhan/miniconda3/envs/RGI/lib/python3.6/site-packages/app/MainBase.py", line 1, in <module>
    from app.settings import *
  File "/home/drasadukhan/miniconda3/envs/RGI/lib/python3.6/site-packages/app/settings.py", line 7, in <module>
    from Bio.Alphabet import generic_dna
  File "/home/drasadukhan/miniconda3/envs/RGI/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

Could you kindly help me in getting over this error?

**Comment by raphenya** [comment]
@yasiromics RGI requires `biopython 1.78`, see https://github.com/arpcard/rgi/issues/124
