### ISSUE TITLE
ValueError: zero-size array to reduction operation fmin which has no identity

### ISSUE THREAD

**Issue by neelam19051** [arpcard/rgi#188]
Hi, i am trying to run rgi heatmap and it gives following error.

**rgi heatmap --input /home/bvs/Neelam/rgi/res_test --output out**

Traceback (most recent call last):
  File "/home/bvs/.local/bin/rgi", line 4, in <module>
    MainBase()
  File "/home/bvs/.local/lib/python3.8/site-packages/app/MainBase.py", line 82, in __init__
    getattr(self, args.command)()
  File "/home/bvs/.local/lib/python3.8/site-packages/app/MainBase.py", line 336, in heatmap
    self.heatmap_run(args)
  File "/home/bvs/.local/lib/python3.8/site-packages/app/MainBase.py", line 357, in heatmap_run
    obj.run()
  File "/home/bvs/.local/lib/python3.8/site-packages/app/Heatmap.py", line 836, in run
    g = sns.heatmap(df, cmap=custom_cmap, cbar=False, norm=norm) #linewidth=0.5
  File "/home/bvs/.local/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/bvs/.local/lib/python3.8/site-packages/seaborn/matrix.py", line 540, in heatmap
    plotter = _HeatMapper(data, vmin, vmax, cmap, center, robust, annot, fmt,
  File "/home/bvs/.local/lib/python3.8/site-packages/seaborn/matrix.py", line 159, in __init__
    self._determine_cmap_params(plot_data, vmin, vmax,
  File "/home/bvs/.local/lib/python3.8/site-packages/seaborn/matrix.py", line 198, in _determine_cmap_params
    vmin = np.nanmin(calc_data)
  File "<__array_function__ internals>", line 180, in nanmin
  File "/home/bvs/.local/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 344, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)
**ValueError: zero-size array to reduction operation fmin which has no identity**

Thank you!

**Comment by pbelmann** [comment]
I get the same error when running rgi version 6.0.1:

```
rgi main --input_sequence input.faa                --output_file  out2/out.rgi --input_type protein --local                --alignment_tool DIAMOND --num_threads 28 --clean --include_loose
rgi heatmap --input out2/ --output test 
``` 

I attached the input files for the rgi heatmap command: [rgi_bug.tar.gz](https://github.com/arpcard/rgi/files/10533776/rgi_bug.tar.gz)

**Comment by matheusgarciaufg** [comment]
I have the same problem

**Comment by raphenya** [comment]
@pbelmann your hits are all Loose hits and the current heatmap does not add Loose hits to the plot. I'm guessing @neelam19051 might have similar scenario. Cheers.
