### ISSUE TITLE
KeyError: 'Antibiotic+Adjuvant'

### ISSUE THREAD

**Issue by neelam19051** [arpcard/rgi#191]
Hi, i am getting this error when i try to run rgi parser ...

sh rgi1.sh
/home/bvs/Neelam/annotated/faa_json/P_aeruginosa_1.faa.json
Traceback (most recent call last):
  File "rgi", line 4, in <module>
    MainBase()
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 82, in __init__
    getattr(self, args.command)()
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 140, in parser
    self.parser_run(args)
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 147, in parser_run
    app.Parser.api_main(args)
  File "/home/bvs/Neelam/rgi/app/Parser.py", line 273, in api_main
    res = make_json(m,j,args.loose,args.type, snps)
  File "/home/bvs/Neelam/rgi/app/Parser.py", line 189, in make_json
    ndict['Best_Hit_ARO_classes'][j[orf][hsp]['ARO_category'][key]['category_aro_class_name']].append(j[orf][hsp]['ARO_category'][key]['category_aro_name'])
KeyError: 'Antibiotic+Adjuvant'
/home/bvs/Neelam/annotated/faa_json/P_aeruginosa_12939.faa.json
Traceback (most recent call last):
  File "rgi", line 4, in <module>
    MainBase()
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 82, in __init__
    getattr(self, args.command)()
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 140, in parser
    self.parser_run(args)
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 147, in parser_run
    app.Parser.api_main(args)
  File "/home/bvs/Neelam/rgi/app/Parser.py", line 273, in api_main
    res = make_json(m,j,args.loose,args.type, snps)
  File "/home/bvs/Neelam/rgi/app/Parser.py", line 189, in make_json
    ndict['Best_Hit_ARO_classes'][j[orf][hsp]['ARO_category'][key]['category_aro_class_name']].append(j[orf][hsp]['ARO_category'][key]['category_aro_name'])
KeyError: 'Antibiotic+Adjuvant'

thank you

**Comment by raphenya** [comment]
@neelam19051 The `rgi parser` is used to create the JSON for the RGI wheel on the website. Currently, the `Antibiotic+Adjuvant` categories are not added to the wheel.
