### ISSUE TITLE
test.sh errors

### ISSUE THREAD

**Issue by LarsDu** [arpcard/rgi#20]
The tests keep failing. I can't quite figure out what is going wrong here.
```
(larsdu_centrifuge) [ldu@login01-adm rgi]$ sh test.sh
--2018-06-26 13:26:05--  https://card.mcmaster.ca/latest/data
Resolving card.mcmaster.ca... 130.113.77.126
Connecting to card.mcmaster.ca|130.113.77.126|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2513777 (2.4M) [application/x-bzip2]
Saving to: “card_data.tar.bz2”

100%[===========================================================================================>] 2,513,777   2.93M/s   in 0.8s

2018-06-26 13:26:06 (2.93 MB/s) - “card_data.tar.bz2” saved [2513777/2513777]

./
./nucleotide_fasta_protein_overexpression_model.fasta
./nucleotide_fasta_protein_knockout_model.fasta
./aro_index.csv
./protein_fasta_protein_variant_model.fasta
./snps.txt
./nucleotide_fasta_rRNA_gene_variant_model.fasta
./aro_categories.csv
./card.json
./protein_fasta_protein_knockout_model.fasta
./nucleotide_fasta_protein_homolog_model.fasta
./protein_fasta_protein_overexpression_model.fasta
./nucleotide_fasta_protein_variant_model.fasta
./protein_fasta_protein_homolog_model.fasta
./CARD-Download-README.txt
./aro_categories_index.csv
======================================================== test session starts ========================================================
platform linux -- Python 3.6.5, pytest-3.6.2, py-1.5.3, pluggy-0.6.0 -- /gpfs/home/ldu/miniconda3/envs/larsdu_centrifuge/bin/python
cachedir: ../.pytest_cache
rootdir: /gpfs/home/ldu/card_db/rgi, inifile:
collected 8 items

test_1.py::test_rgi_protein_sequence FAILED                                                                                   [ 12%]
test_1.py::test_rgi_nucleotide_sequence FAILED                                                                                [ 25%]
test_1.py::test_rgi_homolog_model FAILED                                                                                      [ 37%]
test_1.py::test_rgi_variant_model FAILED                                                                                      [ 50%]
test_1.py::test_rgi_overexpression_model FAILED                                                                               [ 62%]
test_1.py::test_rgi_effluxpump_model FAILED                                                                                   [ 75%]
test_1.py::test_rgi_rrna_model PASSED                                                                                         [ 87%]
test_3.py::test_create_local_db PASSED                                                                                        [100%]

============================================================= FAILURES ==============================================================
_____________________________________________________ test_rgi_protein_sequence _____________________________________________________

rgi = <app.MainBase.MainBase object at 0x7f9bb77a7e80>

    def test_rgi_protein_sequence(rgi):
    	filename = "protein.fasta"
    	output_file = os.path.join(working_directory,outputs,"{}.json".format(filename))
    	run_rgi(rgi, 'protein', os.path.join(working_directory,inputs,filename), output_file)

>   	assert validate_results(output_file, 100, 'NDM-1', 'Perfect') == True
E    AssertionError: assert False == True
E     +  where False = validate_results('/gpfs/home/ldu/card_db/rgi/tests/outputs/protein.fasta.json', 100, 'NDM-1', 'Perfect')

test_1.py:75: AssertionError
___________________________________________________ test_rgi_nucleotide_sequence ____________________________________________________

rgi = <app.MainBase.MainBase object at 0x7f9bb759f208>

    def test_rgi_nucleotide_sequence(rgi):

    	filename = "NC_020818.1.fasta"
    	output_file = os.path.join(working_directory,outputs,"{}.json".format(filename))
    	run_rgi(rgi, 'contig', os.path.join(working_directory,inputs,filename), output_file)

>   	assert validate_results(output_file, 100, 'NDM-1', 'Perfect') == True
E    AssertionError: assert False == True
E     +  where False = validate_results('/gpfs/home/ldu/card_db/rgi/tests/outputs/NC_020818.1.fasta.json', 100, 'NDM-1', 'Perfect')

test_1.py:83: AssertionError
______________________________________________________ test_rgi_homolog_model _______________________________________________________

rgi = <app.MainBase.MainBase object at 0x7f9bb75faef0>

    def test_rgi_homolog_model(rgi):

    	filename = "homolog.fasta"
    	output_file = os.path.join(working_directory,outputs,"{}.json".format(filename))
    	run_rgi(rgi, 'contig', os.path.join(working_directory,inputs,filename), output_file)

>   	assert validate_results(output_file, 100, 'NDM-1', 'Perfect') == True
E    AssertionError: assert False == True
E     +  where False = validate_results('/gpfs/home/ldu/card_db/rgi/tests/outputs/homolog.fasta.json', 100, 'NDM-1', 'Perfect')

test_1.py:94: AssertionError
______________________________________________________ test_rgi_variant_model _______________________________________________________

rgi = <app.MainBase.MainBase object at 0x7f9bb75fa978>

    def test_rgi_variant_model(rgi):

    	filename = "variant.fasta"
    	output_file = os.path.join(working_directory,outputs,"{}.json".format(filename))
    	run_rgi(rgi, 'protein', os.path.join(working_directory,inputs,filename), output_file)

>   	assert validate_results(output_file, 99.88, 'Escherichia coli gyrB conferring resistance to aminocoumarin', 'Strict') == True
E    AssertionError: assert False == True
E     +  where False = validate_results('/gpfs/home/ldu/card_db/rgi/tests/outputs/variant.fasta.json', 99.88, 'Escherichia coli gyrB conferring resistance to aminocoumarin', 'Strict')

test_1.py:102: AssertionError
___________________________________________________ test_rgi_overexpression_model ___________________________________________________

rgi = <app.MainBase.MainBase object at 0x7f9bb75fa860>

    def test_rgi_overexpression_model(rgi):

    	filename = "overexpression.fasta"
    	output_file = os.path.join(working_directory,outputs,"{}.json".format(filename))
    	run_rgi(rgi, 'protein', os.path.join(working_directory,inputs,filename), output_file)

>   	assert validate_results(output_file, 100, 'nalC', 'Strict') == True
E    AssertionError: assert False == True
E     +  where False = validate_results('/gpfs/home/ldu/card_db/rgi/tests/outputs/overexpression.fasta.json', 100, 'nalC', 'Strict')

test_1.py:110: AssertionError
_____________________________________________________ test_rgi_effluxpump_model _____________________________________________________

rgi = <app.MainBase.MainBase object at 0x7f9bb75fa2b0>

    def test_rgi_effluxpump_model(rgi):

    	filename = "effluxpump.fasta"
    	output_file = os.path.join(working_directory,outputs,"{}.json".format(filename))
    	run_rgi(rgi, 'protein', os.path.join(working_directory,inputs,filename), output_file)

>   	assert validate_results(output_file, 100, 'MexA', 'Perfect') == True
E    AssertionError: assert False == True
E     +  where False = validate_results('/gpfs/home/ldu/card_db/rgi/tests/outputs/effluxpump.fasta.json', 100, 'MexA', 'Perfect')

test_1.py:119: AssertionError
================================================ 6 failed, 2 passed in 53.25 seconds ================================================
```

**Comment by LarsDu** [comment]
This command also fails
``` 
rgi main --input_sequence tests/inputs/protein.fasta --output_file test_output_protein_ladu --input_type protein
```

```
Traceback (most recent call last):
  File "/gpfs/home/ldu/miniconda3/envs/larsdu_centrifuge/bin/rgi", line 4, in <module>
    __import__('pkg_resources').run_script('RGI==4.0.3', 'rgi')
  File "/gpfs/home/ldu/miniconda3/envs/larsdu_centrifuge/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gpfs/home/ldu/miniconda3/envs/larsdu_centrifuge/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1425, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/rgi' not found in metadata at '/gpfs/home/ldu/miniconda3/envs/larsdu_centrifuge/lib/python3.6/site-packages/RGI-4.0.3-py3.6.egg-info'
```

**Comment by arpcard** [comment]
@LarsDu are you still getting this error?

**Comment by arpcard** [comment]
@LarsDu please re-open this issue if you have the same problem.

**Comment by XinCao-JNU** [comment]
I get the same error

**Comment by XinCao-JNU** [comment]
I get the same error 
collected 8 items                                                                         

test_1.py::test_rgi_protein_sequence FAILED                                         [ 12%]
test_1.py::test_rgi_nucleotide_sequence FAILED                                      [ 25%]
test_1.py::test_rgi_homolog_model FAILED                                            [ 37%]
test_1.py::test_rgi_variant_model FAILED                                            [ 50%]
test_1.py::test_rgi_overexpression_model FAILED                                     [ 62%]
test_1.py::test_rgi_effluxpump_model FAILED                                         [ 75%]
test_1.py::test_rgi_rrna_model PASSED                                               [ 87%]
test_3.py::test_create_local_db PASSED                                              [100%]

======================================== FAILURES =========================================
________________________________ test_rgi_protein_sequence ________________________________

rgi = <app.MainBase.MainBase object at 0x7f9dcf16bc50>

    def test_rgi_protein_sequence(rgi):
    
    	filename = "protein.fasta"
    	output_file = os.path.join(working_directory,outputs,"{}.json".format(filename))
    	run_rgi(rgi, 'protein', os.path.join(working_directory,inputs,filename), output_file)
    
>   	assert validate_results(output_file, 100, 'NDM-1', 'Perfect') == True
E    AssertionError: assert False == True
E     +  where False = validate_results('/home/Acer1/caoxin/RGI/rgi-4.2.0/tests/outputs/protein.fasta.json', 100, 'NDM-1', 'Perfect')

test_1.py:76: AssertionError
but i can run rgi 
[root@localhost rgi-4.2.0]# rgi main --input_sequence /home/Acer1/caoxin/data/RNA019CDSnew-blasted-proteins.fasta --output_file /home/Acer1/caoxin/data/RNA019CDSnew-blasted-proteins-rgi4.2 --input_type protein.

**Comment by MohamedRefaat92** [comment]
Hi,
Has anyone figured out how to fix this error, yet? 
I get the same error and don't know where to look for a solution.

**Comment by LarsDu** [comment]
Have you made sure the dependencies match versions precisely?
I found that this program is incredibly sensitive to having the exact versions of the following:
Prodigal v2.6.3
NCBI BLAST v2.6.0+
DIAMOND v0.8.36
Python 3.6
