### ISSUE TITLE
RGI Heatmap category

### ISSUE THREAD

**Issue by kayobianco** [arpcard/rgi#236]
I'm trying to use the command "rgi heatmap -clus both -cat drug_class -i "$output_dir" -o "$heatmap_output"" but the -cat command has problems and output is as below:
File "/home/kayobianco/miniconda3/envs/rgi/bin/rgi", line 4, in <module>
     MainBase()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 83, in __init__
     getattr(self, args.command)()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 346, in heatmap
     self.heatmap_run(args)
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 365, in heatmap_run
     obj.run()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 438, in run
     df = self.create_categories(drug_class, df)
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 97, in create_categories
     df = df.append([df.loc[model]]*(len(class_dict[model])-1))
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
     return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
Traceback (most recent call last):
   File "/home/kayobianco/miniconda3/envs/rgi/bin/rgi", line 4, in <module>
     MainBase()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 83, in __init__
     getattr(self, args.command)()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 346, in heatmap
     self.heatmap_run(args)
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 365, in heatmap_run
     obj.run()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 438, in run
     df = self.create_categories(drug_class, df)
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 97, in create_categories
     df = df.append([df.loc[model]]*(len(class_dict[model])-1))
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
     return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
Traceback (most recent call last):
   File "/home/kayobianco/miniconda3/envs/rgi/bin/rgi", line 4, in <module>
     MainBase()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 83, in __init__
     getattr(self, args.command)()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 346, in heatmap
     self.heatmap_run(args)
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/MainBase.py", line 365, in heatmap_run
     obj.run()
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 438, in run
     df = self.create_categories(drug_class, df)
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/app/Heatmap.py", line 97, in create_categories
     df = df.append([df.loc[model]]*(len(class_dict[model])-1))
   File "/home/kayobianco/miniconda3/envs/rgi/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
     return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by dukz** [comment]
I resolved this by downgrading the `pandas` package to 1.5.3.

```
conda install pandas=1.5.3
```
