### ISSUE TITLE
Sample.fasta.temp.draft file not found

### ISSUE THREAD

**Issue by jenniferlu717** [arpcard/rgi#242]
Hello,

I am trying to run rgi on a set of metagenomic samples. The command I run is

`rgi main --input_sequence SAMPLE.fasta --output_file testing --local --clean --low-quality`

However, anytime I run this command, I end up with this error:

> File "/usr/local/lib/python3.10/dist-packages/app/ORF.py", line 28, in contig_to_orf
>     self.orf_prodigal()
> File "/usr/local/lib/python3.10/dist-packages/app/ORF.py", line 73, in orf_prodigal
>     os.remove(os.path.join(self.working_directory, "{}.temp.draft".format(filename)))
> FileNotFoundError: [Errno 2] No such file or directory: 'SAMPLE.fasta.temp.draft'

**Comment by raphenya** [comment]
@jenniferlu717 This looks like prodigal is not installed. Also, the option `--low-quality` should be `--low_quality`. I tested with rgi 5.2.1 and 6.0.1. I will need more information to thoroughly test this, e.g., which version of rgi and what type of sequence is in `SAMPLE.fasta`.

**Comment by rvincenzi** [comment]
I have the same problem. How can I check if it is everything ok with prodigal?

**Comment by gezmi** [comment]
I encountered the same issue, with an installation that was working for years perfectly, so I am absolutely clueless on what could have happened...

The above error comes when I use --clean. If I do not, it changes to the error below:

```
 rgi main -d plasmid -t contig --local -a blast  --input_sequence /home/incfinder/incfinder/storage/app/public/db/fasta/CP131692.fasta --output_file CP131692 --debug
INFO 2024-04-28 00:35:35,941 : /home/incfinder/incfinder/storage/app/public/db/fasta/CP131692.fasta => None
INFO 2024-04-28 00:35:36,096 : valid nucleotide fasta: {'A': 45670, 'T': 42376, 'G': 50029, 'C': 46161, 'N': 0, 'U': 0, 'W': 0, 'S': 0, 'M': 0, 'K': 0, 'R': 0, 'Y': 0, 'B': 0, 'D': 0, 'H': 0, 'V': 0}
INFO 2024-04-28 00:35:36,096 : blast DB exists
INFO 2024-04-28 00:35:36,096 : diamond DB exists
INFO 2024-04-28 00:35:36,099 : minimum sequence length: 184236, maximun sequence length 184236, number of sequences: 1
ERROR 2024-04-28 00:35:36,109 : failed to write orf file
Traceback (most recent call last):
  File "/home/incfinder/anaconda3/envs/rgi/lib/python3.6/site-packages/app/RGI.py", line 286, in process_contig
    if os.stat(contig_fsa_file).st_size > 0:
FileNotFoundError: [Errno 2] No such file or directory: '/home/incfinder/incfinder/CP131692.fasta.temp.contig.fsa'
INFO 2024-04-28 00:35:36,110 : run filter
ERROR 2024-04-28 00:35:36,110 : missing blast xml file(). Please check if input_type: 'contig' correspond with input file: '/home/incfinder/incfinder/storage/app/public/db/fasta/CP131692.fasta' or use '--low_quality' flag for short contigs to predicts partial genes.
INFO 2024-04-28 00:35:36,110 : Total running time 0.169s

```

**Comment by agmcarthur** [comment]
New report @raphenya
