### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_hashtable)

### ISSUE THREAD

**Issue by rotheconrad** [arpcard/rgi#53]
I installed RGI into a conda environment and ran it with this command:
`rgi main --input_sequence 01_Genomes/E_coli_group_FMT1.fna --output_file FMT1_RGI --input_type contig --include_loose --clean`

This seemed to work, I get a json and txt file as output. The json file is 292 MB and the website colorwheel visualization has a limit of 20MB. So I'm uncertain about this file size? So I tried to generate a heatmap. I have 6 genomes I am looking at. When I run this command:

`rgi heatmap --input RGI_CARD/ --output rgi_heatmap.png -clus both`

It throws this error:

`dynamic module does not define module export function (PyInit_hashtable)
Traceback (most recent call last):
  File "/gpfs/pace2/project/bio-konstantinidis/rconrad6/apps/miniconda3/envs/rgi/bin/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/gpfs/pace2/project/bio-konstantinidis/rconrad6/apps/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 16, in <module>
    from app.Heatmap import Heatmap
  File "/gpfs/pace2/project/bio-konstantinidis/rconrad6/apps/miniconda3/envs/rgi/lib/python3.6/site-packages/app/Heatmap.py", line 3, in <module>
    import pandas as pd
  File "/usr/local/pacerepov1/python/2.7/gcc-4.9.0/lib/python2.7/site-packages/pandas-0.15.2-py2.7-linux-x86_64.egg/pandas/__init__.py", line 7, in <module>
    from . import hashtable, tslib, lib
ImportError: dynamic module does not define module export function (PyInit_hashtable)`

**Comment by raphenya** [comment]
@rotheconrad `rgi heatmap` does not include loose hits when plotting. I wasn't able to reproduce this error. If you can please share the results files (without loose hits).

**Comment by raphenya** [comment]
@rotheconrad Do you still have this issue?

**Comment by raphenya** [comment]
@rotheconrad closing issue, please let us know if you need more help on this.
