### ISSUE TITLE
Error of python process...JSONDecodeError

### ISSUE THREAD

**Issue by LiguanLi** [arpcard/rgi#55]
Hi CARD team,

Thanks very much for your amazing work on the database!

I have been using RGI for annotation for a while, now running into some error (start running for 1-2 hours and then stop with error without any output files). The error might be very obvious (sorry for disturbing for such obvious question) but I still can not figure out... 

RGI was installed in conda environment, here is the command line for running (run on prodigal predicted protein sequences):
rgi main --input_sequence "$BASEDIR"/"$TEST"/AssemblyFatNode/"$TEST"_orf.faa --output_file "$OUTDIR"/"$TEST"_rgi --input_type protein --include_loose --clean

The error info was copied as below:
Process Process-2:
Traceback (most recent call last):
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/site-packages/app/Filter.py", line 92, in prepare_output
    obj.combine_jsons()
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/site-packages/app/ConvertRGIJsonToTSV.py", line 38, in combine_jsons
    homolog = json.load(hf)
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/projects/cu_10108/Bin/Programs/Miniconda3/envs/rgi/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thanks a lot!

**Comment by raphenya** [comment]
@LiguanLi this looks like the input is not being read in. Can you also include `--debug` flag.

**Comment by LiguanLi** [comment]
Hi, thanks a lot for quick reply! 

I added --debug flag and error again. The error output has been attached. Thanks very much for helping on this!

[card_annotation_stderr.txt](https://github.com/arpcard/rgi/files/3426088/card_annotation_stderr.txt)

**Comment by raphenya** [comment]
@LiguanLi is it possible to email us the input file at card@mcmaster.ca?

**Comment by LiguanLi** [comment]
Hi Amos, 
Thanks! I have shared the file with you by email. Pls check.
Also tried  myself to figure out the issue. Probably just memory run out. I split 560M fasta file (~1450000 ORFs) into 5 sub-fasta files. RGI has been successfully run on each sub-files. I am thinking to split files, run RGI and merge.
Not sure I really solve the problem or not. Maybe you can help to confirm. Much appreciate!
Best,
Liguan

**Comment by raphenya** [comment]
@LiguanLi Looking at your log file. It does look like memory error. Splitting the input file should resolve this issue.

**Comment by LiguanLi** [comment]
Thanks a lot! Problem solved:)
