### ISSUE TITLE
RrnaModel.py IndexError: string index out of range

### ISSUE THREAD

**Issue by boulund** [arpcard/rgi#59]
I just encountered this error when running RGI version 5.0.0 with biopython 1.72 and blastn 2.9.0:

```
Traceback (most recent call last):
  File "/home/fredrik.boulund/.conda/envs/resistance2/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/fredrik.boulund/.conda/envs/resistance2/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fredrik.boulund/.conda/envs/resistance2/lib/python3.6/site-packages/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home/fredrik.boulund/.conda/envs/resistance2/lib/python3.6/site-packages/app/RrnaModel.py", line 113, in run
    query_snps = {"original": hsp.query[d], "change": hsp.sbjct[d], "position": (d - 1)}
IndexError: string index out of range
```

**Comment by raphenya** [comment]
@boulund Can you try running tests that come with rgi?

**Comment by boulund** [comment]
Not sure how to run the tests. I couldn't find them in the conda installation directory (`~/.conda/envs/resistance/lib/python3.6/site-packages/app` -- why did you use the folder name `app` btw? very confusing!)

To run the tests I cloned the repo into a new folder and changed in to the `tests` folder. There I downloaded the CARD data and prepared `card.json`, following the instructions here: https://github.com/arpcard/rgi#load-card-reference-data
```
wget https://card.mcmaster.ca/latest/data
tar -xvf data ./card.json
rgi load --card_json /path/to/card.json --local
```
I then tried running the tests, but most of them failed due to rgi not finding the local database, so I modified the run commands in the test files as such:
```
diff --git a/tests/test_1.py b/tests/test_1.py                                        
index 45c691a..a405fe0 100644                                                         
--- a/tests/test_1.py                                                                 
+++ b/tests/test_1.py                                                                 
@@ -62,6 +62,7 @@ def run_rgi(rgi, input_type, input_sequence, output_file):          
                '--input_sequence', input_sequence,                                   
                '--output_file', output_file,                                         
                '--alignment_tool', alignment_tool,                                   
+        '--local',                                                                   
                '--clean',                                                            
                '--include_loose',                                                    
                '--low_quality',                                                      
diff --git a/tests/test_4.py b/tests/test_4.py                                        
index c50bb4a..1d5c8c4 100644                                                         
--- a/tests/test_4.py                                                                 
+++ b/tests/test_4.py                                                                 
@@ -25,6 +25,7 @@ def run_rgi(rgi, read_one, read_two, aligner, threads, output_file):
                '--aligner', aligner,                                                 
                '--threads', threads,                                                 
                '--output_file', output_file,                                         
+        '--local',                                                                   
                '--clean',                                                            
                '--debug'                                                             
     ]))                                                                              
```
Then the tests ran, but some still failed. See attached files. 
[test_1.failed.log](https://github.com/arpcard/rgi/files/3475540/test_1.failed.log)
[test_1.log](https://github.com/arpcard/rgi/files/3475541/test_1.log)
[test_2.log](https://github.com/arpcard/rgi/files/3475542/test_2.log)
[test_3.failed.log](https://github.com/arpcard/rgi/files/3475543/test_3.failed.log)
[test_3.log](https://github.com/arpcard/rgi/files/3475544/test_3.log)
[test_4.failed.log](https://github.com/arpcard/rgi/files/3475545/test_4.failed.log)

**Comment by raphenya** [comment]
> (~/.conda/envs/resistance/lib/python3.6/site-packages/app -- why did you use the folder name app btw? very confusing

We didn't mean to confuse. The rgi application directory structure looks like so:
```
$ tree -L 2 -d
.
├── app
│   ├── _data
│   ├── _db
│   └── diff
├── docs
├── images
└── tests
    ├── inputs
    └── outputs
```

`app` contains source files, data and db files. We are always improving our software. Please let us know how to improve the structure.

> And then, after activating I manually uninstalled blast version 2.6.0 from the environment, without removing any other dependencies: conda uninstall --force blast. I have a system-wide installation of blast version 2.9.0 that it will use instead.

RGI was tested with blast version 2.6.0. We are planning on testing newer versions. For now please use version 2.6.0 for rgi.

> Not sure how to run the tests.

I ran the following: 

#### step 1 - setting the environment
``` 
# download the installer (linux) 64 bit,  Python 3.7
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# miniconda install via bash
bash Miniconda3-latest-Linux-x86_64.sh
rm Miniconda3-latest-Linux-x86_64.sh

# follow the prompts on the installer screens
# If you are unsure about any setting, accept the defaults. You can change them later.

# To make the changes take effect, close and then re-open your terminal window.

# Testing your installation, run command conda list
conda list 

# To create an environment from file (env.yaml)

touch env.yaml

echo "name: resistance" >>  env.yaml
echo "channels:" >> env.yaml
echo "  - conda-forge" >> env.yaml
echo "  - bioconda" >> env.yaml
echo "  - defaults" >> env.yaml
echo "dependencies:" >> env.yaml
echo "  - rgi=5.0.0" >> env.yaml
echo "  - biopython=1.72" >> env.yaml

conda env create -f env.yaml
rm env.yaml

# might need to initialize using the following
# conda init bash

echo "To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'."


echo "IMPORTANT: run conda activate resistance manually after conda init"
```

#### step 2 - run tests (please note that you can replace the test file with your own

``` 
# run manually activate environment
#conda activate resistance

# conda environment:
echo "# conda environment: " 
conda info 
echo ""

# list installed packages
echo "# list installed packages: " 
conda list -n resistance 
echo ""

# export active environment to a log file
echo "export active environment to a log file: "
conda env export 
echo ""

# download and load data

wget https://card.mcmaster.ca/latest/data
tar xvf data ./card.json && rm data
rgi load -i card.json --debug --local
rm card.json

wget https://raw.githubusercontent.com/arpcard/rgi/master/tests/inputs/homolog.fasta

# run rgi with debug on
echo "# run rgi with debug on: " 
rgi main \
    --input_sequence homolog.fasta \
    --output_file homolog.fasta.output \
    --input_type contig \
    --num_threads 4 \
    --alignment_tool DIAMOND \
    --local \
    --low_quality \
    --clean \
    --debug 

echo ""
echo "Done."
```

**Comment by boulund** [comment]
> `app` contains source files, data and db files. We are always improving our software. Please let us know how to improve the structure.

Regarding the folder structure, the common way to name the application folder inside a repo is to use the project name (see e.g. https://packaging.python.org/tutorials/packaging-projects/). That way, the application will be installed in an easily identifiable and suitably named folder in the environment's `site-packages` folder. In the case of RGI, a suitable folder name might be `rgi`? (of course care should be taken to avoid name collisions, but a quick search on PyPi yielded no obvious clashes: https://pypi.org/search/?q=rgi).

---------------------
I followed your instructions and created an env like this:
```
name: rgitest
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rgi=5.0.0
  - biopython=1.72
```

Here are my results from running `rgi` with `--debug`. The script I ran is attached below.
```
bash run_tests.sh | tee rgi_tests.log
```
[rgi_tests.log](https://github.com/arpcard/rgi/files/3495595/rgi_tests.log)
[run_tests.sh.txt](https://github.com/arpcard/rgi/files/3495605/run_tests.sh.txt)

Of course, this produced errors with blast no being able to load `libssl.so.1.0.0`, since conda didn't install OpenSSL 1.0.

**Comment by raphenya** [comment]
@boulund hmm... I'm getting this error. I ran on both Mac OS and Linux (Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-140-generic x86_64)). 

@agmcarthur @bpalcock @fmaguire and @apetkau can you help me test this for me? Cheers.

**Comment by karoraw1** [comment]
I got the same issue.
It only occured in 5-10 of the ~150 samples I've analyzed, but rrna mutations are still detectable when the error is present. 

```
INFO 2019-09-20 23:46:56,140 : /scratch/users/karoraw1@jhu.edu/__CA__/CA_V3/data/02_ASSEMBLY_final/CAMPY25_contigs_fixed.fa => None
INFO 2019-09-20 23:46:56,252 : valid nucleotide fasta: {'A': 53424, 'T': 55368, 'G': 21847, 'C': 29746, 'N': 0, 'U': 0, 'W': 0, 'S': 0, 'M': 0, 'K': 0, 'R': $
INFO 2019-09-20 23:46:56,252 : blast DB exists
INFO 2019-09-20 23:46:56,253 : diamond DB exists
INFO 2019-09-20 23:46:56,259 : minimum sequence length: 128, maximun sequence length 160385, number of sequences: 155
INFO 2019-09-20 23:47:05,772 : work with file /scratch/users/karoraw1@jhu.edu/__CA__/CA_V3/data/02_ASSEMBLY_final/CAMPY25_contigs_fixed.fa.temp.contig.fsa
INFO 2019-09-20 23:47:05,772 : run blast
INFO 2019-09-20 23:47:17,554 : set blast xml file: [/scratch/users/karoraw1@jhu.edu/__CA__/CA_V3/data/02_ASSEMBLY_final/CAMPY25_contigs_fixed.fa.temp.contig.$
INFO 2019-09-20 23:47:17,554 : run filter
INFO 2019-09-20 23:47:17,565 : homolog_worker started...
INFO 2019-09-20 23:47:17,567 : variant_worker started...
INFO 2019-09-20 23:47:17,569 : overexpression_worker started...
INFO 2019-09-20 23:47:17,571 : rRNA process: contig
INFO 2019-09-20 23:47:17,571 : rRNA process
INFO 2019-09-20 23:47:17,585 : create_db_query
INFO 2019-09-20 23:47:17,585 : DB from user query
INFO 2019-09-20 23:47:17,776 : blast_reference_to_db_query
INFO 2019-09-20 23:47:18,136 : done running blastn -> /scratch/users/karoraw1@jhu.edu/__CA__/CA_V3/data/02_ASSEMBLY_final/CAMPY25_contigs_fixed.fa.temp.db
Process Process-1:4:
Traceback (most recent call last):
  File "/home-3/karoraw1@jhu.edu/.conda/envs/rgi_new/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home-3/karoraw1@jhu.edu/.conda/envs/rgi_new/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home-3/karoraw1@jhu.edu/.conda/envs/rgi_new/lib/python3.6/site-packages/RGI-5.1.0-py3.6.egg/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home-3/karoraw1@jhu.edu/.conda/envs/rgi_new/lib/python3.6/site-packages/RGI-5.1.0-py3.6.egg/app/RrnaModel.py", line 113, in run
    query_snps = {"original": hsp.query[d], "change": hsp.sbjct[d], "position": (d - 1)}
IndexError: string index out of range
INFO 2019-09-20 23:47:21,428 : save overexpression results...
INFO 2019-09-20 23:47:21,769 : save variant results...
INFO 2019-09-20 23:47:22,252 : save homolog results...
INFO 2019-09-20 23:47:22,276 : prepare output(s) for input: /scratch/users/karoraw1@jhu.edu/__CA__/CA_V3/data/02_ASSEMBLY_final/CAMPY25_contigs_fixed.fa
INFO 2019-09-20 23:47:22,721 : Total running time 26.583s
INFO 2019-09-20 23:47:22,722 : Clean up skipped.
```

**Comment by raphenya** [comment]
@karoraw1 will you be able to share file `CAMPY25_contigs_fixed.fa` so that we can use to debug?
if you can please send it to card@mcmaster.ca. Cheers.

**Comment by karoraw1** [comment]
done @raphenya 

if it didn’t go through, lemme know.

**Comment by jfourquet2** [comment]
Hi,
I had the same issue with my data:
```
Process Process-1:4:
Traceback (most recent call last):
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/site-packages/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/site-packages/app/RrnaModel.py", line 113, in run
    query_snps = {"original": hsp.query[d], "change": hsp.sbjct[d], "position": (d - 1)}
IndexError: string index out of range
WARNING 2019-11-05 05:46:20,909 : partial gene in card reference: aad(6), start_codon: GAG,  stop_codon: TGA
```
I wanted to fixed this creating a conda env like this:
```
name: resistance2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rgi=5.0.0
  - biopython=1.72
  - openssl=1.0
```
But it didn't worked when I run rgi main on data test:
```
rgi main \
     --input_sequence homolog.fasta \
     --output_file homolog.fasta.output \
     --input_type contig \
     --num_threads 4 \
     --alignment_tool DIAMOND \
     --local \
     --low_quality \
     --clean \
     --debug 
INFO 2019-11-05 10:49:53,079 : /work/jfourquet/RGI_tests_2/homolog.fasta => None
INFO 2019-11-05 10:49:53,231 : valid nucleotide fasta: {'A': 14771, 'T': 14410, 'G': 9084, 'C': 8833, 'N': 0, 'U': 0}
INFO 2019-11-05 10:49:53,442 : create blast DB.
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
INFO 2019-11-05 10:49:53,527 : create diamond DB.
INFO 2019-11-05 10:49:53,825 : minimum sequence length: 47098, maximun sequence length 47098, number of sequences: 1
INFO 2019-11-05 10:49:54,541 : work with file /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa
INFO 2019-11-05 10:49:55,796 : done running diamond blastp -> /work/jfourquet/RGI_tests_2/localDB
INFO 2019-11-05 10:49:55,796 : set blast xml file: [/work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa.blastRes.xml]
INFO 2019-11-05 10:49:55,796 : run filter
INFO 2019-11-05 10:49:55,823 : overexpression_worker started...
INFO 2019-11-05 10:49:55,824 : variant_worker started...
INFO 2019-11-05 10:49:55,825 : rRNA process: contig
INFO 2019-11-05 10:49:55,831 : rRNA process
INFO 2019-11-05 10:49:55,827 : homolog_worker started...
INFO 2019-11-05 10:49:55,837 : create_db_query
INFO 2019-11-05 10:49:55,837 : DB from user query
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
INFO 2019-11-05 10:49:55,907 : blast_reference_to_db_query
blastn: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
INFO 2019-11-05 10:49:55,994 : done running blastn -> /work/jfourquet/RGI_tests_2/homolog.fasta.temp.db
Process Process-1:4:
INFO 2019-11-05 10:49:56,561 : save variant results...
Traceback (most recent call last):
  File "/home/jfourquet/.conda/envs/resistance/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jfourquet/.conda/envs/resistance/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jfourquet/.conda/envs/resistance/lib/python3.6/site-packages/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home/jfourquet/.conda/envs/resistance/lib/python3.6/site-packages/app/RrnaModel.py", line 35, in run
    with open(os.path.join(self.xml_file), 'r') as result_handle:
FileNotFoundError: [Errno 2] No such file or directory: '/work/jfourquet/RGI_tests_2/homolog.fasta.temp.blastRes.rrna.xml'
INFO 2019-11-05 10:49:56,575 : save overexpression results...
INFO 2019-11-05 10:49:56,594 : save homolog results...
INFO 2019-11-05 10:49:56,615 : prepare output(s) for input: /work/jfourquet/RGI_tests_2/homolog.fasta
INFO 2019-11-05 10:49:56,625 : Total running time 3.546s
INFO 2019-11-05 10:49:56,627 : Cleaning up temporary files...homolog.fasta
INFO 2019-11-05 10:49:56,627 : /work/jfourquet/RGI_tests_2
INFO 2019-11-05 10:49:56,628 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.potentialGenes
INFO 2019-11-05 10:49:56,628 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.predictedGenes.protein.json
INFO 2019-11-05 10:49:56,629 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.predictedGenes.json
INFO 2019-11-05 10:49:56,629 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp
INFO 2019-11-05 10:49:56,629 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.overexpression.json
INFO 2019-11-05 10:49:56,630 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa.blastRes.xml
INFO 2019-11-05 10:49:56,630 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.homolog.json
INFO 2019-11-05 10:49:56,631 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa
INFO 2019-11-05 10:49:56,631 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.variant.json
INFO 2019-11-05 10:49:56,631 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contigToORF.fsa
INFO 2019-11-05 10:49:56,632 : /work/jfourquet/RGI_tests_2
```
So I create a new environment with this .yaml file because I already had this openssl issue:
```
name: resistance2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rgi=5.0.0
  - biopython=1.72
  - openssl=1.0
```
And after activation of this new env resistance2, rgi main run well on data test:
```
rgi main \
     --input_sequence homolog.fasta \
     --output_file homolog.fasta.output \
     --input_type contig \
     --num_threads 4 \
     --alignment_tool DIAMOND \
     --local \
     --low_quality \
     --clean \
     --debug
INFO 2019-11-05 11:14:05,277 : /work/jfourquet/RGI_tests_2/homolog.fasta => None
INFO 2019-11-05 11:14:05,417 : valid nucleotide fasta: {'A': 14771, 'T': 14410, 'G': 9084, 'C': 8833, 'N': 0, 'U': 0}
INFO 2019-11-05 11:14:05,578 : create blast DB.
INFO 2019-11-05 11:14:06,900 : create diamond DB.
INFO 2019-11-05 11:14:07,198 : minimum sequence length: 47098, maximun sequence length 47098, number of sequences: 1
INFO 2019-11-05 11:14:08,028 : work with file /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa
INFO 2019-11-05 11:14:09,297 : done running diamond blastp -> /work/jfourquet/RGI_tests_2/localDB
INFO 2019-11-05 11:14:09,297 : set blast xml file: [/work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa.blastRes.xml]
INFO 2019-11-05 11:14:09,297 : run filter
INFO 2019-11-05 11:14:09,317 : overexpression_worker started...
INFO 2019-11-05 11:14:09,319 : variant_worker started...
INFO 2019-11-05 11:14:09,326 : rRNA process: contig
INFO 2019-11-05 11:14:09,320 : homolog_worker started...
INFO 2019-11-05 11:14:09,329 : rRNA process
INFO 2019-11-05 11:14:09,331 : create_db_query
INFO 2019-11-05 11:14:09,332 : DB from user query
INFO 2019-11-05 11:14:09,430 : blast_reference_to_db_query
INFO 2019-11-05 11:14:09,919 : save overexpression results...
INFO 2019-11-05 11:14:09,928 : save variant results...
INFO 2019-11-05 11:14:09,940 : save homolog results...
INFO 2019-11-05 11:14:11,311 : done running blastn -> /work/jfourquet/RGI_tests_2/homolog.fasta.temp.db
INFO 2019-11-05 11:14:11,481 : rRNA process Done.
INFO 2019-11-05 11:14:11,492 : prepare output(s) for input: /work/jfourquet/RGI_tests_2/homolog.fasta
INFO 2019-11-05 11:14:11,502 : Total running time 6.225s
INFO 2019-11-05 11:14:11,503 : Cleaning up temporary files...homolog.fasta
INFO 2019-11-05 11:14:11,503 : /work/jfourquet/RGI_tests_2
INFO 2019-11-05 11:14:11,504 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.rrna.json
INFO 2019-11-05 11:14:11,505 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.potentialGenes
INFO 2019-11-05 11:14:11,505 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.predictedGenes.protein.json
INFO 2019-11-05 11:14:11,505 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.predictedGenes.json
INFO 2019-11-05 11:14:11,506 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp
INFO 2019-11-05 11:14:11,506 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.blastRes.rrna.xml
INFO 2019-11-05 11:14:11,506 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.overexpression.json
INFO 2019-11-05 11:14:11,507 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.db.nhr
INFO 2019-11-05 11:14:11,507 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa.blastRes.xml
INFO 2019-11-05 11:14:11,507 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.homolog.json
INFO 2019-11-05 11:14:11,507 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.db.nin
INFO 2019-11-05 11:14:11,508 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contig.fsa
INFO 2019-11-05 11:14:11,508 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.variant.json
INFO 2019-11-05 11:14:11,508 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.db.nsq
INFO 2019-11-05 11:14:11,508 : Removed file: /work/jfourquet/RGI_tests_2/homolog.fasta.temp.contigToORF.fsa
INFO 2019-11-05 11:14:11,509 : /work/jfourquet/RGI_tests_2
```

**Comment by jfourquet2** [comment]
Hi,
Finally I run rgi main with my data and I have the same issue:
```
INFO 2019-11-05 11:26:20,974 : /work/jfourquet/metaspades-scaffolds.fasta => None
INFO 2019-11-05 11:26:21,676 : valid nucleotide fasta: {'A': 317721, 'T': 318837, 'G': 208140, 'C': 215574, 'N': 10, 'U': 0}
INFO 2019-11-05 11:26:21,678 : blast DB exists
INFO 2019-11-05 11:26:21,679 : diamond DB exists
INFO 2019-11-05 11:26:30,518 : minimum sequence length: 56, maximun sequence length 1060282, number of sequences: 621442
INFO 2019-11-05 12:47:43,339 : work with file /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.contig.fsa
INFO 2019-11-05 12:48:17,866 : done running diamond blastp -> /work/jfourquet/RGI_tests_2/localDB
INFO 2019-11-05 12:48:17,867 : set blast xml file: [/work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.contig.fsa.blastRes.xml]
INFO 2019-11-05 12:48:17,867 : run filter
INFO 2019-11-05 12:48:17,899 : homolog_worker started...
INFO 2019-11-05 12:48:17,904 : variant_worker started...
INFO 2019-11-05 12:48:17,909 : overexpression_worker started...
INFO 2019-11-05 12:48:17,911 : rRNA process: contig
INFO 2019-11-05 12:48:17,911 : rRNA process
INFO 2019-11-05 12:48:29,616 : create_db_query
INFO 2019-11-05 12:48:29,616 : DB from user query
INFO 2019-11-05 12:48:56,580 : blast_reference_to_db_query
INFO 2019-11-05 12:49:00,300 : done running blastn -> /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.db
Process Process-1:4:
Traceback (most recent call last):
  File "/home/jfourquet/.conda/envs/resistance2/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jfourquet/.conda/envs/resistance2/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jfourquet/.conda/envs/resistance2/lib/python3.6/site-packages/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home/jfourquet/.conda/envs/resistance2/lib/python3.6/site-packages/app/RrnaModel.py", line 113, in run
    query_snps = {"original": hsp.query[d], "change": hsp.sbjct[d], "position": (d - 1)}
IndexError: string index out of range
WARNING 2019-11-05 12:50:45,483 : partial gene in card reference: aad(6), start_codon: GAG,  stop_codon: TGA
INFO 2019-11-05 12:51:56,852 : save overexpression results...
INFO 2019-11-05 12:52:35,488 : save homolog results...
INFO 2019-11-05 12:52:53,178 : save variant results...
INFO 2019-11-05 12:52:53,240 : prepare output(s) for input: /work/jfourquet/metaspades-scaffolds.fasta
INFO 2019-11-05 12:52:53,551 : Total running time 5192.592s
INFO 2019-11-05 12:52:53,551 : Cleaning up temporary files...b_rgi
INFO 2019-11-05 12:52:53,551 : /work/jfourquet/RGI_tests_2
INFO 2019-11-05 12:52:53,552 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.contigToORF.fsa
INFO 2019-11-05 12:52:53,553 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.predictedGenes.protein.json
INFO 2019-11-05 12:52:53,553 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.overexpression.json
INFO 2019-11-05 12:52:53,553 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.contig.fsa.blastRes.xml
INFO 2019-11-05 12:52:53,554 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.db.nsq
INFO 2019-11-05 12:52:53,568 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.db.nin
INFO 2019-11-05 12:52:53,569 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.variant.json
INFO 2019-11-05 12:52:53,569 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.contig.fsa
INFO 2019-11-05 12:52:53,570 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.potentialGenes
INFO 2019-11-05 12:52:53,571 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.predictedGenes.json
INFO 2019-11-05 12:52:53,571 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.blastRes.rrna.xml
INFO 2019-11-05 12:52:53,571 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.homolog.json
INFO 2019-11-05 12:52:53,571 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp
INFO 2019-11-05 12:52:53,572 : Removed file: /work/jfourquet/RGI_tests_2/metaspades-scaffolds.fasta.temp.db.nhr
INFO 2019-11-05 12:52:53,572 : /work/jfourquet/RGI_tests_2
```
Did you have an idea of the source of the issue ?
Thanks a lot in advance !

**Comment by raphenya** [comment]
@jfourquet2 @boulund Yes, this is indeed a bug. I will use @karoraw1 file to resolve this. Thank you for your patience

**Comment by jfourquet2** [comment]
Thanks a lot !

**Comment by jfourquet2** [comment]
Thanks a lot, the issue with RrnaModel.py is fixed with your last commit !
