### ISSUE TITLE
Openssl 1.0.0 error issue

### ISSUE THREAD

**Issue by Lamm-a** [arpcard/rgi#74]
I have installed rgi using the guidance on issue #31 and all the databases are correctly installed to my knowledge.

when I run the following command inside a bash script:
`rgi main -i ~/ABR/Genomes_original_bins/bin.100.fa -o ~/ABR/Genomes_original_bins/rgi-output/ -t contig --include_loose --low_quality --clean`

I get the following error:
```
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/lamma/miniconda3/envs/rgi/bin/rgi", line 4, in <module>
    MainBase()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 54, in __init__
    getattr(self, args.command)()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 59, in main
    self.main_run(args)
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 91, in main_run
    rgi_obj.run()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/RGI.py", line 138, in run
    self.run_blast()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/RGI.py", line 185, in run_blast
    self.process_contig()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/RGI.py", line 217, in process_contig
    orf_obj.contig_to_orf()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/ORF.py", line 18, in contig_to_orf
    self.orf_prodigal()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/ORF.py", line 31, in orf_prodigal
    _min, _max = self.min_max_sequence_length()
  File "/home/lamma/miniconda3/envs/rgi/lib/python3.6/site-packages/app/ORF.py", line 25, in min_max_sequence_length
    return min(sequences), max(sequences)
ValueError: min() arg is an empty sequence
```

I have looked for an openssl 1.0.0 but none are avaliable on any conda channels i can find. This error is rendoring rgi unusable and I am struggling to find any fix. My environment is the following:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
biopython                 1.74             py36h516909a_0    conda-forge
blast                     2.6.0               boost1.64_2    bioconda
boost                     1.64.0                   py36_4    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py36_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
diamond                   0.8.36               hdbcaa40_3    bioconda
expat                     2.2.5             he1b5a44_1003    conda-forge
filetype                  1.0.5                      py_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
importlib_metadata        0.23                     py36_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
matplotlib                3.1.1                    py36_0    conda-forge
matplotlib-base           3.1.1            py36hfd891ef_0    conda-forge
mock                      3.0.5                    py36_0    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.2           py36h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.1           py36hb3f55d8_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pip                       19.3                     py36_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
prodigal                  2.6.3                         1    bioconda
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyahocorasick             1.4.0            py36h14c3975_0    conda-forge
pyfaidx                   0.5.5.2                    py_1    bioconda
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py36hcca6a23_4    conda-forge
pytest                    5.2.1                    py36_0    conda-forge
python                    3.6.7             h357f687_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rgi                       4.2.2            py36ha92aebf_1    bioconda
scipy                     1.3.1            py36h921218d_2    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
setuptools                41.4.0                   py36_0    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
statsmodels               0.10.1           py36hc1659b7_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tornado                   6.0.3            py36h516909a_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
````

Is there a fix for this issue?

**Comment by jfourquet2** [comment]
Hello,
I have the same issue, did you fixed it for your analysis?
My command line:
`rgi main -i Sample_metaspades-scaffolds.fasta -o Sample_rgi -t contig --local`
The issue:
`makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`
Thanks a lot in advance!

**Comment by jfourquet2** [comment]
If it could help, I solved my issue with the post [#57 ]: my conda installation of rgi is done with:
`conda install -c bioconda rgi=5.1.0 openssl=1.0`

**Comment by jfourquet2** [comment]
I had a new issue:
Process Process-1:4:
Traceback (most recent call last):
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/site-packages/app/Filter.py", line 121, in process_rrna
    res = rrna_obj.run()
  File "/home/jfourquet/.conda/envs/env_rgi_openssl/lib/python3.6/site-packages/app/RrnaModel.py", line 113, in run
    query_snps = {"original": hsp.query[d], "change": hsp.sbjct[d], "position": (d - 1)}
IndexError: string index out of range
WARNING 2019-11-05 05:46:20,909 : partial gene in card reference: aad(6), start_codon: GAG,  stop_codon: TGA
If it could help, I use the post #59 to fixed this problem.

**Comment by raphenya** [comment]
The latest tag 5.1.0--py_1 at https://quay.io/repository/biocontainers/rgi?tab=tags resolves these issues.

**Comment by jfourquet2** [comment]
Thanks !
