### ISSUE TITLE
rgi heatmap error

### ISSUE THREAD

**Issue by darwinbandoy** [arpcard/rgi#76]
While I cannot use rgi in Mac, I was able to generate results in a linux (Xeon Processors) conda environment.

However, I was trying rgi heatmap -h but there are no help options with the heatmap.

Is the heatmap already deprecated?

**Comment by darwinbandoy** [comment]
I was able to ran heatmap -h options on Mac conda environment. However  I have this error message:

ValueError: zero-size array to reduction operation minimum which has no identity

And the details are here: 

Traceback (most recent call last):
  File "/Users/miniconda3/envs/rgi/bin/rgi", line 4, in <module>
    MainBase()
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 54, in __init__
    getattr(self, args.command)()
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 260, in heatmap
    self.heatmap_run(args)
  File "/Users/drbandoy/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 281, in heatmap_run
    obj.run()
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/Heatmap.py", line 871, in run
    g = sns.heatmap(df, cmap='viridis', cbar=False) #linewidth=0.5
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/seaborn/matrix.py", line 517, in heatmap
    yticklabels, mask)
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/seaborn/matrix.py", line 167, in __init__
    cmap, center, robust)
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/seaborn/matrix.py", line 206, in _determine_cmap_params
    vmin = np.percentile(calc_data, 2) if robust else calc_data.min()
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by raphenya** [comment]
> Is the heatmap already deprecated?

No, we have heatmap for RGI version 5.1.0 working. Details availble here https://github.com/arpcard/rgi#generating-heat-maps-of-rgi-main-results

Can you try installing rgi using yaml file. Try something like so:

#### file env.yaml:

```
name: rgi510
channels:       
  - conda-forge 
  - bioconda    
  - defaults     
dependencies:   
  - rgi=5.1.0 
```

#### create environment using:
```conda env create -f env.yaml```

**Comment by darwinbandoy** [comment]
This solution solved the issue. I think the conda installation settings (on conda website) is restricting the version to 3.1
