### ISSUE TITLE
rgi parser error 

### ISSUE THREAD

**Issue by darwinbandoy** [arpcard/rgi#77]
I ran rgi parser on the json output on Mac OS conda of rgi but I get this error message:

Traceback (most recent call last):
  File "/Users/miniconda3/envs/rgi/bin/rgi", line 4, in <module>
    MainBase()
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 54, in __init__
    getattr(self, args.command)()
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 110, in parser
    self.parser_run(args)
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/MainBase.py", line 117, in parser_run
    app.Parser.api_main(args)
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/Parser.py", line 269, in api_main
    m = main(j)
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/Parser.py", line 53, in main
    best_hsp = max(hsp.keys(), key=(lambda key: hsp[key]['bit_score']))
  File "/Users/miniconda3/envs/rgi/lib/python3.6/site-packages/app/Parser.py", line 53, in <lambda>
    best_hsp = max(hsp.keys(), key=(lambda key: hsp[key]['bit_score']))
KeyError: 'bit_score'

**Comment by raphenya** [comment]
@darwinbandoy `rgi parser` is used to create JSON files for the wheel from JSON files produced by `rgi main`.

This looks like the bit_score is not set. It might be related to this issue #56

**Comment by neelam19051** [comment]
Hi i am trying to run rgi  and it giving following error, please have a look.

rgi parser -i /home/bvs/Neelam/rgi/out -o output8 --type contig
Traceback (most recent call last):
  File "./rgi", line 4, in <module>
    MainBase()
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 82, in __init__
    getattr(self, args.command)()
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 140, in parser
    self.parser_run(args)
  File "/home/bvs/Neelam/rgi/app/MainBase.py", line 147, in parser_run
    app.Parser.api_main(args)
  File "/home/bvs/Neelam/rgi/app/Parser.py", line 269, in api_main
    j = read_file(args.input)
  File "/home/bvs/Neelam/rgi/app/Parser.py", line 24, in read_file
    with open(os.path.join("{}".format(j))) as f:
**IsADirectoryError: [Errno 21] Is a directory: '/home/bvs/Neelam/rgi/out'**

Thank you
