### ISSUE TITLE
heatmap -clus both not working

### ISSUE THREAD

**Issue by debaleena-bhowmik** [arpcard/rgi#90]
I ran the following command after installation of rgi in my ubuntu system.

rgi heatmap -i all_json_ref_seq/ -o output1 -clus both

The folder all_json_ref_seq/ contains the .json output of rgi main.

The following error appeared.

Traceback (most recent call last):
  File "/home/bioinfo2/miniconda3/envs/rgiDB/bin/rgi", line 4, in <module>
    MainBase()
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/app/MainBase.py", line 81, in __init__
    getattr(self, args.command)()
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/app/MainBase.py", line 323, in heatmap
    self.heatmap_run(args)
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/app/MainBase.py", line 344, in heatmap_run
    obj.run()
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/app/Heatmap.py", line 815, in run
    df = self.cluster_data(self.cluster, df)
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/app/Heatmap.py", line 194, in cluster_data
    cm = sns.clustermap(df, row_cluster=True, col_cluster=True)
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/seaborn/matrix.py", line 1366, in clustermap
    tree_kws=tree_kws, **kwargs)
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/seaborn/matrix.py", line 1183, in plot
    tree_kws=tree_kws)
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/seaborn/matrix.py", line 1029, in plot_dendrograms
    tree_kws=tree_kws
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/seaborn/matrix.py", line 747, in dendrogram
    label=label, rotate=rotate)
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/seaborn/matrix.py", line 559, in __init__
    self.linkage = self.calculated_linkage
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/seaborn/matrix.py", line 626, in calculated_linkage
    return self._calculate_linkage_scipy()
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/seaborn/matrix.py", line 595, in _calculate_linkage_scipy
    metric=self.metric)
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/scipy/cluster/hierarchy.py", line 1064, in linkage
    n = int(distance.num_obs_y(y))
  File "/home/bioinfo2/miniconda3/envs/rgiDB/lib/python3.6/site-packages/scipy/spatial/distance.py", line 2403, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.

**Comment by raphenya** [comment]
@debaleena-bhowmik I tested this with RGI version 5.1.0 and I didn't get this error. Please see attached file to test on your system:

[issue_90.zip](https://github.com/arpcard/rgi/files/4704894/issue_90.zip)

Cheers.
