### ISSUE TITLE
loading CARD in RGI

### ISSUE THREAD

**Issue by AroArz** [arpcard/rgi#91]
Hi!

Just want to notify you of some weird issues with conda install.

`conda create -n RGI python=3.6`
`conda activate RGI`
`conda install -c bioconda rgi`

Worked fine to install rgi on virtual environment but after downloading CARD and trying to load it locally I get

```
(RGI) [aroarz@rackham1 RGI]$ rgi load --card_json card.json --local
Traceback (most recent call last):
  File "/home/aroarz/miniconda3/envs/RGI/bin/rgi", line 11, in <module>
    import package.rgi.rgi
  File "/home/aroarz/miniconda3/envs/RGI/lib/python3.6/site-packages/package/rgi/rgi.py", line 158
    print "DB exists"
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("DB exists")?
```

**Comment by AroArz** [comment]
Sorry, just noticed that the issue comes from 

'conda install -c bioconda rgi' as that loads rgi=3.1.0

Using ´conda install --channel bioconda --channel conda-forge rgi` I'm able to get the 4.2.2 version. and can then load the database.
