### ISSUE TITLE
libssl.so.1.0.0 is missing from the biocontainers version of rgi 5.{1,0}.0

### ISSUE THREAD

**Issue by mahesh-panchal** [arpcard/rgi#92]
Hi, I'm trying to run `rgi` within a singularity container generated from the biocontainers image, but it's failing due to a missing library for `makeblastdb`.

I've tried these images so far:
```
singularity pull docker://quay.io/biocontainers/rgi:5.1.0--py36hed695b0_0
singularity pull docker://quay.io/biocontainers/rgi:5.0.0--py36hed695b0_0
```

I launch the image using:
```
singularity shell -e ../../singularity/quay.io-biocontainers-rgi-5.1.0--py36hed695b0_0.img
```
And then run the commands:
```
rgi load --card_json card.json --local
rgi main -i DA34821_pseudomolecule.fasta -o DA34821_rgi -n 1 --local
```
(-n = 1 for testing purposes).
`rgi main` then results in the following error:
```
Singularity> rgi main -i DA34821_pseudomolecule.fasta -o DA34821_rgi -n 1 --local
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
blastp: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
ERROR 2020-03-26 15:06:23,652 : missing blast xml file(/crex/proj/snic2020-16-48/nobackup/nxf-work/46/a5a6e06155843b82ccd453639d4caa/DA34821_pseudomolecule.fasta.temp.contig.fsa.blastRes.xml). Please check if input_type: 'contig' correspond with input file: '/crex/proj/snic2020-16-48/nobackup/nxf-work/46/a5a6e06155843b82ccd453639d4caa/DA34821_pseudomolecule.fasta' or use '--low_quality' flag for short contigs to predicts partial genes.
```

I also tried using this biocontainers image:
```
singularity pull docker://quay.io/biocontainers/rgi:5.1.0--py_1
```
but that results in another error:
```
Singularity> rgi load --card_json card.json --local                                                     
Traceback (most recent call last):
  File "/usr/local/bin/rgi", line 2, in <module>
    from app.MainBase import MainBase
  File "/usr/local/lib/python3.6/site-packages/app/MainBase.py", line 16, in <module>
    from app.Heatmap import Heatmap
  File "/usr/local/lib/python3.6/site-packages/app/Heatmap.py", line 9, in <module>
    import seaborn as sns
  File "/usr/local/lib/python3.6/site-packages/seaborn/__init__.py", line 9, in <module>
    from .relational import *
  File "/usr/local/lib/python3.6/site-packages/seaborn/relational.py", line 18, in <module>
    from .axisgrid import FacetGrid, _facet_docs
  File "/usr/local/lib/python3.6/site-packages/seaborn/axisgrid.py", line 15, in <module>
    from .distributions import distplot, kdeplot,  _freedman_diaconis_bins
  File "/usr/local/lib/python3.6/site-packages/seaborn/distributions.py", line 14, in <module>
    import statsmodels.nonparametric.api as smnp
  File "/usr/local/lib/python3.6/site-packages/statsmodels/nonparametric/api.py", line 7, in <module>
    from .kde import KDEUnivariate
  File "/usr/local/lib/python3.6/site-packages/statsmodels/nonparametric/kde.py", line 21, in <module>
    from .linbin import fast_linbin
  File "__init__.pxd", line 918, in init statsmodels.nonparametric.linbin
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

Could the `openssl` package be added as a dependency to the conda recipe please? (I just saw issue #48).

Regards,
Mahesh.

**Comment by mahesh-panchal** [comment]
Sorry, I just realized this is the responsibility of the blast conda package maintainers.
